# AH Plugin - Configurações Gerais
language: "pt" # Opções: "en", "pt"
debug-mode: false

# Integração Discord
# Cole a URL do Webhook do seu canal do Discord abaixo
discord-webhook: "SUA_URL_DO_WEBHOOK_AQUI"

# Configurações do Leilão
auction:
  expire-time-hours: 48
  selling-tax: 0.05
  minimum-price: 10.0
  max-items-per-player: 28

# Configurações de Interface
gui:
  main-menu-title: "&8Auction House - Categorias"
  search-title: "&8Pesquisar item por nome/ID"
