name: AH
version: '1.0'
main: com.comonier.ah.AH
api-version: '1.21'
author: Comonier
description: Plugin de Auction House modular com sistema de categorias e busca.
bootstrapper: com.comonier.ah.AH
load: POSTWORLD
dependencies:
  server:
    Vault:
      load: BEFORE
      required: true
